### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by danny007in** [gotbahn/browsers-support-badges#164]

**Comment by crashmax-dev** [comment]
http://gotbahn.github.io/browsers-support-badges/

**Comment by gotbahn** [comment]
Sorry @danny007in, I changed my username and didn't update this project. Updated refs, should be available under https://gotbahn.github.io/browsers-support-badges as @crashmax-dev pointed.

**Comment by popoway** [comment]
Hello @gotbahn, the markdown link generated by the website also refers to the old username. Thanks!
